jobs:
- job: Linux
  displayName: linux-latest
  pool:
    vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        GCC-8 Debug:
          CC: gcc-8
          CXX: g++-8
          BuildType: Debug
          SelfHost: false
          CMakeArgs: ''

        GCC-8 Release:
          CC: gcc-8
          CXX: g++-8
          BuildType: Release
          SelfHost: false
          CMakeArgs: ''
    steps:
      - script: |
          sudo apt-get 
          update sudo apt-get install -y libc++-dev libc++abi-dev libc++abi1 libstdc++-8-dev gcc-8 g++-8
          
          CMAKE_CXX_FLAGS="-std=c++17"
          if [[ "$CXX" == clang++* ]]; then CMAKE_CXX_FLAGS+=" -stdlib=libstdc++"; fi

        displayName: 'Install dependencies'
      - task: CMake@1
        inputs:
          cmakeArgs: '.. $(CMakeArgs) -DCMAKE_BUILD_TYPE=$(BuildType) -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS" -DSNMALLOC_CI_BUILD=On'
        workingDirectory: build
        failOnStderr: true
        displayName: 'Build'